services:
  db:
    image: postgres:18
    container_name: incidentdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: incidentdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: incidentapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=incidentdb;Username=postgres;Password=postgres
      - Jwt__Key=e5ed6032-51a7-48cd-b097-02c3192881f9
      - Jwt__Issuer=IncidentAPI
      - Jwt__Audience=IncidentAPIUsers
      - Jwt__ExpirationMinutes=60
      - Email__Username=jhonxyleh@gmail.com
      - Email__Password=punw dfre nrnq oheg
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
